#!/bin/bash

die_if_no_exists()
{
    which $1 > /dev/null
    if [ $? -ne 0 ]
    then
        echo "$1 is required"
        exit 1
    fi
}

die_if_no_exists latex
die_if_no_exists pdflatex

DOCNAME=document

if [ "$1" == "clean" ]
then
    rm -f *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.ilg *.toc *.ind *.out *.blg *.synctex.gz
else
    latex -src -interaction=nonstopmode $DOCNAME.tex > /dev/null
    pdflatex -synctex=1 -interaction=nonstopmode $DOCNAME.tex > /dev/null
    
    if [ -f $DOCNAME.pdf ]
    then
        echo "Successfully generated $DOCNAME.pdf"
        exit 0
    else
        echo "Failed to generat $DOCNAME.pdf"
        exit 1
    fi
fi
