#!/bin/bash

die_if_no_exists()
{
    which $1 > /dev/null
    if [ $? -ne 0 ]
    then
        echo "$1 is required"
        exit 1
    fi
}

die_if_no_exists texstudio
die_if_no_exists latex
die_if_no_exists pdflatex

echo "Cleaning..."
rm -f *.log *.aux *.dvi *.lof *.lot *.bit *.idx *.glo *.bbl *.ilg *.toc *.ind *.out *.blg *.synctex.gz

texstudio document.tex
